### ISSUE TITLE
Parsing of the data-prop attribute

### ISSUE THREAD

**Issue by contexD** [labd/react-abode#11]
With release `0.3.1` React Abode tries to `JSON.parse` the data-prop attribute and in case of failure simply passes the data-prop attribute unaltered to the React component (as a string). 
In other words, before `0.3.1` all `data-prop` attributes were passed as strings to the React component, since release `0.3.1` they might be of type `object`, `boolean`,`number` etc.

This is a **breaking change** since props assumed to be strings before might not be any longer strings (e.g. `data-prop-id="123"` will be of type `number` but `data-prop-id="0123"` will be of type `string`).

To allow for backward compatibility and JSON parsing of the `data-prop` attribute I see two possibilities: 

1. Limit the parsing of the `data-prop` attribute by **only parsing a subset of valid JSON strings** (e.g. objects and arrays)
2. Allow the user to **pass a** [**reviver parameter**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#using_the_reviver_parameter) in order to transform the parsed `data-prop`.

Are there any other options? What would be possible caveats?
@blurrah @TriPSs @BramKaashoek

**Comment by BramKaashoek** [comment]
My preference would be to release a 0.3.2 with the JSON parsing removed and a 0.4.0 with JSON parsing.

**Comment by blurrah** [comment]
If you're going to do a separate release it should upgrade the major version if it's backwards incompatible, so `1.0.0`

**Comment by BramKaashoek** [comment]
:point_up: true

**Comment by contexD** [comment]
How to handle cases where I need JSON parsing for certain props (e.g. a `customer` JSON string) but want a predictable and consistent data type for other props I pass (e.g. `ids` with potential leading zeros)?

**Comment by tleguijt** [comment]
@contexD the `id` example that you brought up; we define `Props` interface where the properties themselves are typed. Can't we use that information in some way? (type annotations has to be parsed and stored during Typescript compilation, not sure if that is possible)
